package com.jstesta.docstor.util;

import java.util.Arrays;
import java.util.Collection;

/**
 * Created by joseph.testa on 11/17/2017.
 */

final class FileExtensions {

    static final Collection<String> MUSIC_EXTENSIONS = Arrays.asList(
            "3gp",
            "aa",
            "aac",
            "aax",
            "act",
            "aiff",
            "amr",
            "ape",
            "au",
            "awb",
            "dct",
            "dss",
            "dvf",
            "flac",
            "gsm",
            "iklax",
            "ivs",
            "m4a",
            "m4b",
            "m4p",
            "mmf",
            "mp3",
            "mpc",
            "msv",
            "ogg",
            "oga",
            "mogg",
            "opus",
            "ra",
            "rm",
            "raw",
            "sln",
            "tta",
            "vox",
            "wav",
            "wma",
            "wv",
            "webm",
            "8svx"
    );

    static final Collection<String> DOCUMENT_EXTENSIONS = Arrays.asList(
            "txt",
            "doc",
            "html",
            "htm",
            "fb2",
            "docx",
            "doc",
            "odt",
            "oxps",
            "sxw",
            "xml",
            "pdf",
            "ps",
            "rtf",
            "svg",
            "tex",
            "wpd",
            "wp",
            "wp7"
    );

    static final Collection<String> PICTURE_EXTENSIONS = Arrays.asList(
            "3fr",
            "ai",
            "ani",
            "ari",
            "arw",
            "bay",
            "bmp",
            "cap",
            "cgm",
            "cin",
            "cpc",
            "cr2",
            "crw",
            "dcr",
            "dcs",
            "djv",
            "djvu",
            "dng",
            "drf",
            "drw",
            "ecw",
            "eip",
            "erf",
            "exif",
            "exr",
            "fff",
            "fpx",
            "gfa",
            "gif",
            "gs",
            "hdp",
            "icns",
            "ico",
            "iff",
            "iiq",
            "img",
            "ipe",
            "jls",
            "jng",
            "jp2",
            "jpe",
            "jpeg",
            "jpg",
            "jpx",
            "jxr",
            "k25",
            "kdc",
            "lbm",
            "mdc",
            "mef",
            "mng",
            "mos",
            "mrw",
            "nef",
            "nrw",
            "obm",
            "orf",
            "pam",
            "pbm",
            "pcx",
            "pef",
            "pgf",
            "pgm",
            "pic",
            "png",
            "pnm",
            "ppm",
            "psd",
            "ptx",
            "pxn",
            "r3d",
            "raf",
            "ras",
            "raw",
            "rw2"
    );

}
